# Generated by Django 3.0.5 on 2020-04-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin')], default='U', max_length=1),
        ),
    ]
