# Generated by Django 3.0.5 on 2020-04-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
