# Generated by Django 3.0.5 on 2020-04-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop',
        ),
    ]
