# Generated by Django 2.2.2 on 2020-05-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shop.Shop'),
        ),
    ]
